#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrpPluginData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Mrp")]
	public partial class MrpDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertData_Inventory(Data_Inventory instance);
    partial void UpdateData_Inventory(Data_Inventory instance);
    partial void DeleteData_Inventory(Data_Inventory instance);
    partial void InsertSys_Plugin(Sys_Plugin instance);
    partial void UpdateSys_Plugin(Sys_Plugin instance);
    partial void DeleteSys_Plugin(Sys_Plugin instance);
    partial void InsertSys_Plugin_Setting(Sys_Plugin_Setting instance);
    partial void UpdateSys_Plugin_Setting(Sys_Plugin_Setting instance);
    partial void DeleteSys_Plugin_Setting(Sys_Plugin_Setting instance);
    partial void InsertData_Bom(Data_Bom instance);
    partial void UpdateData_Bom(Data_Bom instance);
    partial void DeleteData_Bom(Data_Bom instance);
    partial void InsertData_OrderedPart(Data_OrderedPart instance);
    partial void UpdateData_OrderedPart(Data_OrderedPart instance);
    partial void DeleteData_OrderedPart(Data_OrderedPart instance);
    partial void InsertData_PartVendorConfig(Data_PartVendorConfig instance);
    partial void UpdateData_PartVendorConfig(Data_PartVendorConfig instance);
    partial void DeleteData_PartVendorConfig(Data_PartVendorConfig instance);
    partial void InsertData_ProductionPlan(Data_ProductionPlan instance);
    partial void UpdateData_ProductionPlan(Data_ProductionPlan instance);
    partial void DeleteData_ProductionPlan(Data_ProductionPlan instance);
    #endregion
		
		public MrpDataClassesDataContext() : 
				base(global::MrpPluginData.Properties.Settings.Default.MrpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MrpDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MrpDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MrpDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MrpDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Data_Inventory> Data_Inventory
		{
			get
			{
				return this.GetTable<Data_Inventory>();
			}
		}
		
		public System.Data.Linq.Table<Sys_Plugin> Sys_Plugin
		{
			get
			{
				return this.GetTable<Sys_Plugin>();
			}
		}
		
		public System.Data.Linq.Table<Sys_Plugin_Setting> Sys_Plugin_Setting
		{
			get
			{
				return this.GetTable<Sys_Plugin_Setting>();
			}
		}
		
		public System.Data.Linq.Table<Data_Bom> Data_Bom
		{
			get
			{
				return this.GetTable<Data_Bom>();
			}
		}
		
		public System.Data.Linq.Table<Data_OrderedPart> Data_OrderedPart
		{
			get
			{
				return this.GetTable<Data_OrderedPart>();
			}
		}
		
		public System.Data.Linq.Table<Data_PartVendorConfig> Data_PartVendorConfig
		{
			get
			{
				return this.GetTable<Data_PartVendorConfig>();
			}
		}
		
		public System.Data.Linq.Table<Data_ProductionPlan> Data_ProductionPlan
		{
			get
			{
				return this.GetTable<Data_ProductionPlan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data_Inventory")]
	public partial class Data_Inventory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _partId;
		
		private string _uom;
		
		private System.DateTime _FIFO;
		
		private System.DateTime _expireDate;
		
		private double _quantity;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpartIdChanging(string value);
    partial void OnpartIdChanged();
    partial void OnuomChanging(string value);
    partial void OnuomChanged();
    partial void OnFIFOChanging(System.DateTime value);
    partial void OnFIFOChanged();
    partial void OnexpireDateChanging(System.DateTime value);
    partial void OnexpireDateChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    #endregion
		
		public Data_Inventory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partId
		{
			get
			{
				return this._partId;
			}
			set
			{
				if ((this._partId != value))
				{
					this.OnpartIdChanging(value);
					this.SendPropertyChanging();
					this._partId = value;
					this.SendPropertyChanged("partId");
					this.OnpartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				if ((this._uom != value))
				{
					this.OnuomChanging(value);
					this.SendPropertyChanging();
					this._uom = value;
					this.SendPropertyChanged("uom");
					this.OnuomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIFO", DbType="DateTime NOT NULL")]
		public System.DateTime FIFO
		{
			get
			{
				return this._FIFO;
			}
			set
			{
				if ((this._FIFO != value))
				{
					this.OnFIFOChanging(value);
					this.SendPropertyChanging();
					this._FIFO = value;
					this.SendPropertyChanged("FIFO");
					this.OnFIFOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expireDate", DbType="DateTime NOT NULL")]
		public System.DateTime expireDate
		{
			get
			{
				return this._expireDate;
			}
			set
			{
				if ((this._expireDate != value))
				{
					this.OnexpireDateChanging(value);
					this.SendPropertyChanging();
					this._expireDate = value;
					this.SendPropertyChanged("expireDate");
					this.OnexpireDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_Plugin")]
	public partial class Sys_Plugin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _pluginType;
		
		private string _assemblyFile;
		
		private string _type;
		
		private string _method;
		
		private System.Nullable<int> _seq;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnpluginTypeChanging(string value);
    partial void OnpluginTypeChanged();
    partial void OnassemblyFileChanging(string value);
    partial void OnassemblyFileChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnmethodChanging(string value);
    partial void OnmethodChanged();
    partial void OnseqChanging(System.Nullable<int> value);
    partial void OnseqChanged();
    #endregion
		
		public Sys_Plugin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pluginType", DbType="VarChar(50)")]
		public string pluginType
		{
			get
			{
				return this._pluginType;
			}
			set
			{
				if ((this._pluginType != value))
				{
					this.OnpluginTypeChanging(value);
					this.SendPropertyChanging();
					this._pluginType = value;
					this.SendPropertyChanged("pluginType");
					this.OnpluginTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assemblyFile", DbType="VarChar(50)")]
		public string assemblyFile
		{
			get
			{
				return this._assemblyFile;
			}
			set
			{
				if ((this._assemblyFile != value))
				{
					this.OnassemblyFileChanging(value);
					this.SendPropertyChanging();
					this._assemblyFile = value;
					this.SendPropertyChanged("assemblyFile");
					this.OnassemblyFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method", DbType="VarChar(50)")]
		public string method
		{
			get
			{
				return this._method;
			}
			set
			{
				if ((this._method != value))
				{
					this.OnmethodChanging(value);
					this.SendPropertyChanging();
					this._method = value;
					this.SendPropertyChanged("method");
					this.OnmethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seq", DbType="Int")]
		public System.Nullable<int> seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				if ((this._seq != value))
				{
					this.OnseqChanging(value);
					this.SendPropertyChanging();
					this._seq = value;
					this.SendPropertyChanged("seq");
					this.OnseqChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sys_Plugin_Setting")]
	public partial class Sys_Plugin_Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _value;
		
		private string _pluginName;
		
		private string _type;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OnpluginNameChanging(string value);
    partial void OnpluginNameChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public Sys_Plugin_Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pluginName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pluginName
		{
			get
			{
				return this._pluginName;
			}
			set
			{
				if ((this._pluginName != value))
				{
					this.OnpluginNameChanging(value);
					this.SendPropertyChanging();
					this._pluginName = value;
					this.SendPropertyChanged("pluginName");
					this.OnpluginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data_Bom")]
	public partial class Data_Bom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _bomId;
		
		private string _assemblyPartId;
		
		private string _materialPartId;
		
		private double _quantity;
		
		private string _uom;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbomIdChanging(string value);
    partial void OnbomIdChanged();
    partial void OnassemblyPartIdChanging(string value);
    partial void OnassemblyPartIdChanged();
    partial void OnmaterialPartIdChanging(string value);
    partial void OnmaterialPartIdChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    partial void OnuomChanging(string value);
    partial void OnuomChanged();
    #endregion
		
		public Data_Bom()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bomId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bomId
		{
			get
			{
				return this._bomId;
			}
			set
			{
				if ((this._bomId != value))
				{
					this.OnbomIdChanging(value);
					this.SendPropertyChanging();
					this._bomId = value;
					this.SendPropertyChanged("bomId");
					this.OnbomIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assemblyPartId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string assemblyPartId
		{
			get
			{
				return this._assemblyPartId;
			}
			set
			{
				if ((this._assemblyPartId != value))
				{
					this.OnassemblyPartIdChanging(value);
					this.SendPropertyChanging();
					this._assemblyPartId = value;
					this.SendPropertyChanged("assemblyPartId");
					this.OnassemblyPartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materialPartId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string materialPartId
		{
			get
			{
				return this._materialPartId;
			}
			set
			{
				if ((this._materialPartId != value))
				{
					this.OnmaterialPartIdChanging(value);
					this.SendPropertyChanging();
					this._materialPartId = value;
					this.SendPropertyChanged("materialPartId");
					this.OnmaterialPartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string uom
		{
			get
			{
				return this._uom;
			}
			set
			{
				if ((this._uom != value))
				{
					this.OnuomChanging(value);
					this.SendPropertyChanging();
					this._uom = value;
					this.SendPropertyChanged("uom");
					this.OnuomChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data_OrderedPart")]
	public partial class Data_OrderedPart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _partId;
		
		private string _sourceId;
		
		private double _quantity;
		
		private System.DateTime _arriveTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpartIdChanging(string value);
    partial void OnpartIdChanged();
    partial void OnsourceIdChanging(string value);
    partial void OnsourceIdChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    partial void OnarriveTimeChanging(System.DateTime value);
    partial void OnarriveTimeChanged();
    #endregion
		
		public Data_OrderedPart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partId", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string partId
		{
			get
			{
				return this._partId;
			}
			set
			{
				if ((this._partId != value))
				{
					this.OnpartIdChanging(value);
					this.SendPropertyChanging();
					this._partId = value;
					this.SendPropertyChanged("partId");
					this.OnpartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sourceId", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string sourceId
		{
			get
			{
				return this._sourceId;
			}
			set
			{
				if ((this._sourceId != value))
				{
					this.OnsourceIdChanging(value);
					this.SendPropertyChanging();
					this._sourceId = value;
					this.SendPropertyChanged("sourceId");
					this.OnsourceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_arriveTime", DbType="DateTime NOT NULL")]
		public System.DateTime arriveTime
		{
			get
			{
				return this._arriveTime;
			}
			set
			{
				if ((this._arriveTime != value))
				{
					this.OnarriveTimeChanging(value);
					this.SendPropertyChanging();
					this._arriveTime = value;
					this.SendPropertyChanged("arriveTime");
					this.OnarriveTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data_PartVendorConfig")]
	public partial class Data_PartVendorConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _partId;
		
		private string _vendorId;
		
		private int _leadTime;
		
		private double _moq;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpartIdChanging(string value);
    partial void OnpartIdChanged();
    partial void OnvendorIdChanging(string value);
    partial void OnvendorIdChanged();
    partial void OnleadTimeChanging(int value);
    partial void OnleadTimeChanged();
    partial void OnmoqChanging(double value);
    partial void OnmoqChanged();
    #endregion
		
		public Data_PartVendorConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string partId
		{
			get
			{
				return this._partId;
			}
			set
			{
				if ((this._partId != value))
				{
					this.OnpartIdChanging(value);
					this.SendPropertyChanging();
					this._partId = value;
					this.SendPropertyChanged("partId");
					this.OnpartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendorId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string vendorId
		{
			get
			{
				return this._vendorId;
			}
			set
			{
				if ((this._vendorId != value))
				{
					this.OnvendorIdChanging(value);
					this.SendPropertyChanging();
					this._vendorId = value;
					this.SendPropertyChanged("vendorId");
					this.OnvendorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leadTime", DbType="Int NOT NULL")]
		public int leadTime
		{
			get
			{
				return this._leadTime;
			}
			set
			{
				if ((this._leadTime != value))
				{
					this.OnleadTimeChanging(value);
					this.SendPropertyChanging();
					this._leadTime = value;
					this.SendPropertyChanged("leadTime");
					this.OnleadTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moq", DbType="Float NOT NULL")]
		public double moq
		{
			get
			{
				return this._moq;
			}
			set
			{
				if ((this._moq != value))
				{
					this.OnmoqChanging(value);
					this.SendPropertyChanging();
					this._moq = value;
					this.SendPropertyChanged("moq");
					this.OnmoqChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Data_ProductionPlan")]
	public partial class Data_ProductionPlan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _planId;
		
		private string _assemblyPartId;
		
		private System.DateTime _time;
		
		private double _quantity;
		
		private string _bomId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnplanIdChanging(string value);
    partial void OnplanIdChanged();
    partial void OnassemblyPartIdChanging(string value);
    partial void OnassemblyPartIdChanged();
    partial void OntimeChanging(System.DateTime value);
    partial void OntimeChanged();
    partial void OnquantityChanging(double value);
    partial void OnquantityChanged();
    partial void OnbomIdChanging(string value);
    partial void OnbomIdChanged();
    #endregion
		
		public Data_ProductionPlan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string planId
		{
			get
			{
				return this._planId;
			}
			set
			{
				if ((this._planId != value))
				{
					this.OnplanIdChanging(value);
					this.SendPropertyChanging();
					this._planId = value;
					this.SendPropertyChanged("planId");
					this.OnplanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assemblyPartId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string assemblyPartId
		{
			get
			{
				return this._assemblyPartId;
			}
			set
			{
				if ((this._assemblyPartId != value))
				{
					this.OnassemblyPartIdChanging(value);
					this.SendPropertyChanging();
					this._assemblyPartId = value;
					this.SendPropertyChanged("assemblyPartId");
					this.OnassemblyPartIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime NOT NULL")]
		public System.DateTime time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Float NOT NULL")]
		public double quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bomId", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string bomId
		{
			get
			{
				return this._bomId;
			}
			set
			{
				if ((this._bomId != value))
				{
					this.OnbomIdChanging(value);
					this.SendPropertyChanging();
					this._bomId = value;
					this.SendPropertyChanged("bomId");
					this.OnbomIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
